@startuml
'httpp://plantuml.com/state-diagram

scale 850 width
[*] --> l

state "live" as l
    l: size = saved
    l: scroll = 100
    l: pause false
    l: rate enabled
    l: date today

state "paused" as p
    p: size = input
    p: scroll any
    p: pause true
    p: rate disabled
    p: date today


state "history" as h
    h: size = 24h
    h: scroll enabled
    h: pause true
    h: rate disabled
    h: date past day

l --> p : scroll != 100 || \nonPause = true
p --> l : scroll = 100 || \nonPause = false
l --> h : onDate != today
p --> h : onDate != today
h --> l : onDate = today || \nonPause = false
@enduml