@startuml
'https://plantuml.com/state-diagram

scale 950 width

state "NO_CAR" as noCar
state "WAIT_CAR" as waitCar

state "CAR_CONNECTED" as car {
    state "APP_STOP_TARGET" as appstop {
        state "NOT_CHARGING" as notCh
        state "CHARGE_STOPPING" as stopCh
        state "CHARGE_STOP_FULL" as stopFull
    }
    state "APP_START_TARGET" as appstart {
        state "WHILE_CHARGING" as whileCh {
            state "STARTUP_CHARGING" as startCh
            state "CHARGING" as Ch
            state "FINISH_CHARGING" as finCh
        }
        state "FULLY_CHARGED" as fulCh
    }
    [*] --> notCh
}

noCar -d-> waitCar : B
waitCar -d-> car : C
notCh --> startCh : 0 | 1 | 2
startCh --> startCh : 1 | 2
notCh --> Ch : 3
startCh --> Ch : 3
Ch -> finCh : 4
finCh -->fulCh : 5
stopCh --> notCh : C
fulCh -l-> stopFull: 6
stopFull -u-> notCh : 7

whileCh -u-> stopCh: 4a

car -u-> car: A | B | C

car -u-> noCar : A

@enduml