@startuml
'https://plantuml.com/state-diagram

scale 1200 width

[*] -right-> inAct

state "Inactive" as inAct
state "Active" as act {
    act: entry: WallboxMonitor.subscribeState(this)
    act: exit: WallboxMonitor.unsubscribeState(this)

     [*] -left-> noCar : [noCarConnected]

    state "NoCarConnected" as noCar
'      nocl: entry: cancelCharging()

    state "CarConnected" as carCon {

        state "ChargingStopped" as cStop
            cStop: entry: stopCharging()
            cStop: exit: forceDefaultIfStopped()

        state "ChargePvSurplus" as cSurplus {
          cSurplus: entry: PvChargeStrategy.startStrategy(this)
          cSurplus: entry: stopCharging()
          cSurplus: exit: PvChargeStrategy.stopStrategy(this)
'          cSurplus: exit: stopCharging()

          state "Surplus" as sp {
           sp: exit: stopCharging()

            state "HasSurplus" as hasPlus {
'                hasPlus: entry: setCurrent(v)
                hasPlus: on: surplus(v) : setCurrent(v)
            }

            state "WaitForExtCharge" as waitCh
                waitCh: entry: setCurrent(v)
                waitCh: entry: startCharging()
                waitCh: on: surplus(v) : setCurrent(v)

        }

            state "NoSurplus" as noPlus {
              noPlus: on: noSurplus : ignore
            }

        state lpstart <<start>>

      }

      state "ChargeTibber" as cTibber
      cTibber: entry: startTibberMonitor
      cTibber: exit: stopTibberMonitor
      cTibber: on: tibberGo : startCharging()
      cTibber: on: tibberHalt : stopCharging()


      state "ChargeAnyway" as cAnyway
        cAnyway: entry: startCharging()
        cAnyway: entry: setCurrent(maxCurrent)
        cAnyway: exit:stopCharging()

      state "switch" as choiceCmd <<choice>>

      note top of choiceCmd
        choice has semantic of switch/case,
        \tsee sequence of cases
      end note

      note "anyStop = FullyCharged || \n\tStoppedByCar||\n\tStoppedByApp||\n\tcmdChargeStop" as NcarCon

      [H] -l-> choiceCmd : chargeCmdChanged
      [*] --> choiceCmd
    }
     [*] --> carCon : [isCarConnected]

}
cSurplus -down-> cStop : anyStop
cTibber -down-> cStop : anyStop
cAnyway --> cStop : anyStop
carCon -up-> noCar : carDisconnected

choiceCmd -l-> cSurplus : [4: cmdChargePvSurplus]
choiceCmd --> cAnyway : [2: cmdChargeAnyway]
choiceCmd --> cStop : [1: anyStop]
choiceCmd --> cTibber : [3: cmdChargeTibber]
cStop -up-> choiceCmd : extStartCmd

noCar --> carCon : carConnected
inAct -down-> act : activate
act -up-> inAct : deactivate

noPlus -right-> sp : surplus(v)
waitCh -down-> hasPlus : extChargeCmd
waitCh -down-> hasPlus : [isCharging]
sp -u-> noPlus : noSurplus
lpstart -left-> noPlus

note "CarChargingManager" as NTop

@enduml