@startuml
'https://plantuml.com/state-diagram

scale 1400 width

[*] --> act

state "Active" as act {
    act: entry: startWallboxMonitor()
    act: exit: stopWallboxMonitor()

    state "CannotLoad" as nocl {
'      nocl: entry: cancelLoading()
    }

    state "CanLoad" as cl {
      cl: entry: getLoadStrategy()
'      cl: entry: beginLoading()

      state "LoadTibber" as lt {
      lt: entry: startTibberMonitor
      lt: exit: stopTibberMonitor
      lt: on: tibberGo : startLoading()
      lt: on: tibberHalt : stopLoading()
      }

      state "LoadPvSurplus" as lps {
        lps: entry: startSurplusMonitor()
        lps: exit: stopSurplusMonitor()

        state "HasSurplus" as has {
            has: entry: setCurrent(v)
            has: entry: startLoading()
        }

        state "NoSurplus" as nos {
          nos: entry: stopLoading()
        }
      }
      lps -left-> has : surplus(v)
      lps --> nos : noSurplus

      state "LoadAnyway" as la {
        la: entry: startLoading()
        la: entry: setCurrent(maxCurrent)
      }

        state "LoadStopped" as ls {
        ls: entry: stopLoading()
        }

      cl -up-> ls : loadStop
      cl --> lps : loadPvSurplus
      cl --> lt : loadTibber
      cl --> la : loadAnyway
    }
}
act --> cl : canLoad
act --> nocl : cannotLoad

json LoadStrategy {
    "LoadStrategy": ["NO", "PV", "ANYWAY", "TIBBER"]
}
@enduml