@startuml
'https://plantuml.com/state-diagram

scale 850 width
[*] -right-> inact
state "Inactive" as inact

state "Active" as act {
    act: entry: WallboxMonitor.subscribeState(this)
    act: exit: WallboxMonitor.unsubscribeState(this)

    state "NoCarConnected" as nocar

    state "CarConnected" as carcon {

        state when <<choice>>

        state "ImmediatePlan" as imp {
            imp: entry: planCharging
        }

        state "waitNightData" as wd
        state "dataAvailable" as da
            da: entry: planCharging
        wd --> da : dataAvailable

        state "ExecuteChargingPlan" as xc {
'            xc: entry: this.^nextHour
'            xc: every hour: this.^nextHour
            state isch <<choice>>
            state "charge" as ch
                ch: entry: ^CarChargingManager.tibberGo
                ch: exit: ^CarChargingManager.tibberHalt
            state "idle" as id

            isch -right-> ch : [onHour() == charge]
            isch -left-> id : [onHour() == idle]
            xc -d-> isch : every hour
            [*] -r-> isch
        }

        state "chargingDone" as done

        [*] --> when
        isch -down-> done : [onHour() == done]

    }
    [*] -left-> nocar : [carConnected == false]
    [*] --> carcon  : [carConnected == true]
    nocar -down-> carcon : carConnected

}
when -left-> imp : immediateCharge
when -right-> wd : [nightCharge && noData]
when --> da : [nightCharge && hasData]
da -down-> xc
imp --> xc
carcon --> nocar : carDisconnected
ch -d-> done : fullyCharged
inact -down-> act : activate
act -up-> inact : deactivate
'xc -down-> xc : every Hour

@enduml